repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-import-order",
            "flake8-bugbear",
            "flake8-executable",
            "flake8-rst-docstrings",
            "flake8-docstrings",
            "flake8-builtins",
          ]
