repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.1
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-import-order",
            "flake8-bugbear",
            "flake8-executable",
            "flake8-builtins",
            "flake8-docstrings",
            "flake8-rst-docstrings",
          ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.780'
    hooks:
    -   id: mypy
