name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
      - name: Lint with pre-commit
        run: |
          pre-commit run --all-files
  test:
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Cache
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/test-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/pip_pkgs_dir
          key: ${{ runner.os }}-pip-${{ env.CACHE_NUMBER }} }} # TODO: hash requirements
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r optional-requirements.txt
          python -m pip install -r dev-requirements.txt
      - shell: bash -l {0}
        run: |
          pytest --cov=mwdata --cov-report term-missing --junitxml=junit.xml --cov-report xml tests
