name: CI

on:
  push:
    branches: [master]
    paths:
      - "**.py"
  pull_request:
    branches: [master]
    paths:
      - "**.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit
          python -m pip install mypy
      - name: Lint with pre-commit
        run: |
          pre-commit run --all-files
      - name: mypy check
        run: |
          mypy --config-file mypy.ini
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v1
        env:
          # Increase this value to reset cache if etc/test-environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('etc/test-environment.yml') }}
      - name: Setup miniconda
        uses: goanpeca/setup-miniconda@v1.3.0
        with:
          miniconda-version: latest
          activate-environment: test-env
          environment-file: etc/test-environment.yml
          condarc-file: etc/.condarc
          auto-activate-base: false
      - name: Run unit tests
        shell: bash -l {0}
        run: |
          pip install -e . &&
          pytest --cov=data_describe --cov-report term-missing --junitxml=junit.xml --cov-report xml tests
